// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshData.proto

#include "meshData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr meshData_proto::meshData_proto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : pversion_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , pmeshname_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , vbo_vert_(nullptr)
  , vbo_norm_(nullptr)
  , vbo_uv_(nullptr)
  , vbo_index_(nullptr)
  , vbo_color_(nullptr)
  , vbo_weights_(nullptr)
  , vbo_joints_(nullptr)
  , vbo_invbind_(nullptr)
  , text_color_(nullptr)
  , mode_(0)

  , tricount_(0u)
  , vertcount_(0u){}
struct meshData_protoDefaultTypeInternal {
  constexpr meshData_protoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~meshData_protoDefaultTypeInternal() {}
  union {
    meshData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
bool meshData_proto_RENDER_MODE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> meshData_proto_RENDER_MODE_strings[7] = {};

static const char meshData_proto_RENDER_MODE_names[] =
  "MODE_LINE"
  "MODE_LINE_LOOP"
  "MODE_LINE_STRIP"
  "MODE_POINTS"
  "MODE_TRIANGLES"
  "MODE_TRIANGLE_FAN"
  "MODE_TRIANGLE_STRIP";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry meshData_proto_RENDER_MODE_entries[] = {
  { {meshData_proto_RENDER_MODE_names + 0, 9}, 1 },
  { {meshData_proto_RENDER_MODE_names + 9, 14}, 2 },
  { {meshData_proto_RENDER_MODE_names + 23, 15}, 3 },
  { {meshData_proto_RENDER_MODE_names + 38, 11}, 0 },
  { {meshData_proto_RENDER_MODE_names + 49, 14}, 4 },
  { {meshData_proto_RENDER_MODE_names + 63, 17}, 6 },
  { {meshData_proto_RENDER_MODE_names + 80, 19}, 5 },
};

static const int meshData_proto_RENDER_MODE_entries_by_number[] = {
  3, // 0 -> MODE_POINTS
  0, // 1 -> MODE_LINE
  1, // 2 -> MODE_LINE_LOOP
  2, // 3 -> MODE_LINE_STRIP
  4, // 4 -> MODE_TRIANGLES
  6, // 5 -> MODE_TRIANGLE_STRIP
  5, // 6 -> MODE_TRIANGLE_FAN
};

const std::string& meshData_proto_RENDER_MODE_Name(
    meshData_proto_RENDER_MODE value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          meshData_proto_RENDER_MODE_entries,
          meshData_proto_RENDER_MODE_entries_by_number,
          7, meshData_proto_RENDER_MODE_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      meshData_proto_RENDER_MODE_entries,
      meshData_proto_RENDER_MODE_entries_by_number,
      7, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     meshData_proto_RENDER_MODE_strings[idx].get();
}
bool meshData_proto_RENDER_MODE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, meshData_proto_RENDER_MODE* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      meshData_proto_RENDER_MODE_entries, 7, name, &int_value);
  if (success) {
    *value = static_cast<meshData_proto_RENDER_MODE>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_POINTS;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_LINE;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_LINE_LOOP;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_LINE_STRIP;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_TRIANGLES;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_TRIANGLE_STRIP;
constexpr meshData_proto_RENDER_MODE meshData_proto::MODE_TRIANGLE_FAN;
constexpr meshData_proto_RENDER_MODE meshData_proto::RENDER_MODE_MIN;
constexpr meshData_proto_RENDER_MODE meshData_proto::RENDER_MODE_MAX;
constexpr int meshData_proto::RENDER_MODE_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class meshData_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<meshData_proto>()._has_bits_);
  static void set_has_pversion(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_pmeshname(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_mode(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_tricount(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_vertcount(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static const ::vboData_proto& vbo_vert(const meshData_proto* msg);
  static void set_has_vbo_vert(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static const ::vboData_proto& vbo_norm(const meshData_proto* msg);
  static void set_has_vbo_norm(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static const ::vboData_proto& vbo_uv(const meshData_proto* msg);
  static void set_has_vbo_uv(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static const ::vboData_proto& vbo_index(const meshData_proto* msg);
  static void set_has_vbo_index(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static const ::vboData_proto& vbo_color(const meshData_proto* msg);
  static void set_has_vbo_color(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static const ::vboData_proto& vbo_weights(const meshData_proto* msg);
  static void set_has_vbo_weights(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static const ::vboData_proto& vbo_joints(const meshData_proto* msg);
  static void set_has_vbo_joints(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static const ::vboData_proto& vbo_invbind(const meshData_proto* msg);
  static void set_has_vbo_invbind(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static const ::textureData_proto& text_color(const meshData_proto* msg);
  static void set_has_text_color(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
};

const ::vboData_proto&
meshData_proto::_Internal::vbo_vert(const meshData_proto* msg) {
  return *msg->vbo_vert_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_norm(const meshData_proto* msg) {
  return *msg->vbo_norm_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_uv(const meshData_proto* msg) {
  return *msg->vbo_uv_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_index(const meshData_proto* msg) {
  return *msg->vbo_index_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_color(const meshData_proto* msg) {
  return *msg->vbo_color_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_weights(const meshData_proto* msg) {
  return *msg->vbo_weights_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_joints(const meshData_proto* msg) {
  return *msg->vbo_joints_;
}
const ::vboData_proto&
meshData_proto::_Internal::vbo_invbind(const meshData_proto* msg) {
  return *msg->vbo_invbind_;
}
const ::textureData_proto&
meshData_proto::_Internal::text_color(const meshData_proto* msg) {
  return *msg->text_color_;
}
void meshData_proto::clear_vbo_vert() {
  if (vbo_vert_ != nullptr) vbo_vert_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
void meshData_proto::clear_vbo_norm() {
  if (vbo_norm_ != nullptr) vbo_norm_->Clear();
  _has_bits_[0] &= ~0x00000008u;
}
void meshData_proto::clear_vbo_uv() {
  if (vbo_uv_ != nullptr) vbo_uv_->Clear();
  _has_bits_[0] &= ~0x00000010u;
}
void meshData_proto::clear_vbo_index() {
  if (vbo_index_ != nullptr) vbo_index_->Clear();
  _has_bits_[0] &= ~0x00000020u;
}
void meshData_proto::clear_vbo_color() {
  if (vbo_color_ != nullptr) vbo_color_->Clear();
  _has_bits_[0] &= ~0x00000040u;
}
void meshData_proto::clear_vbo_weights() {
  if (vbo_weights_ != nullptr) vbo_weights_->Clear();
  _has_bits_[0] &= ~0x00000080u;
}
void meshData_proto::clear_vbo_joints() {
  if (vbo_joints_ != nullptr) vbo_joints_->Clear();
  _has_bits_[0] &= ~0x00000100u;
}
void meshData_proto::clear_vbo_invbind() {
  if (vbo_invbind_ != nullptr) vbo_invbind_->Clear();
  _has_bits_[0] &= ~0x00000200u;
}
void meshData_proto::clear_text_color() {
  if (text_color_ != nullptr) text_color_->Clear();
  _has_bits_[0] &= ~0x00000400u;
}
meshData_proto::meshData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:meshData_proto)
}
meshData_proto::meshData_proto(const meshData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  pversion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_pversion()) {
    pversion_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pversion(), 
      GetArenaForAllocation());
  }
  pmeshname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_pmeshname()) {
    pmeshname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_pmeshname(), 
      GetArenaForAllocation());
  }
  if (from._internal_has_vbo_vert()) {
    vbo_vert_ = new ::vboData_proto(*from.vbo_vert_);
  } else {
    vbo_vert_ = nullptr;
  }
  if (from._internal_has_vbo_norm()) {
    vbo_norm_ = new ::vboData_proto(*from.vbo_norm_);
  } else {
    vbo_norm_ = nullptr;
  }
  if (from._internal_has_vbo_uv()) {
    vbo_uv_ = new ::vboData_proto(*from.vbo_uv_);
  } else {
    vbo_uv_ = nullptr;
  }
  if (from._internal_has_vbo_index()) {
    vbo_index_ = new ::vboData_proto(*from.vbo_index_);
  } else {
    vbo_index_ = nullptr;
  }
  if (from._internal_has_vbo_color()) {
    vbo_color_ = new ::vboData_proto(*from.vbo_color_);
  } else {
    vbo_color_ = nullptr;
  }
  if (from._internal_has_vbo_weights()) {
    vbo_weights_ = new ::vboData_proto(*from.vbo_weights_);
  } else {
    vbo_weights_ = nullptr;
  }
  if (from._internal_has_vbo_joints()) {
    vbo_joints_ = new ::vboData_proto(*from.vbo_joints_);
  } else {
    vbo_joints_ = nullptr;
  }
  if (from._internal_has_vbo_invbind()) {
    vbo_invbind_ = new ::vboData_proto(*from.vbo_invbind_);
  } else {
    vbo_invbind_ = nullptr;
  }
  if (from._internal_has_text_color()) {
    text_color_ = new ::textureData_proto(*from.text_color_);
  } else {
    text_color_ = nullptr;
  }
  ::memcpy(&mode_, &from.mode_,
    static_cast<size_t>(reinterpret_cast<char*>(&vertcount_) -
    reinterpret_cast<char*>(&mode_)) + sizeof(vertcount_));
  // @@protoc_insertion_point(copy_constructor:meshData_proto)
}

inline void meshData_proto::SharedCtor() {
pversion_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
pmeshname_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&vbo_vert_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&vertcount_) -
    reinterpret_cast<char*>(&vbo_vert_)) + sizeof(vertcount_));
}

meshData_proto::~meshData_proto() {
  // @@protoc_insertion_point(destructor:meshData_proto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void meshData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  pversion_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  pmeshname_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete vbo_vert_;
  if (this != internal_default_instance()) delete vbo_norm_;
  if (this != internal_default_instance()) delete vbo_uv_;
  if (this != internal_default_instance()) delete vbo_index_;
  if (this != internal_default_instance()) delete vbo_color_;
  if (this != internal_default_instance()) delete vbo_weights_;
  if (this != internal_default_instance()) delete vbo_joints_;
  if (this != internal_default_instance()) delete vbo_invbind_;
  if (this != internal_default_instance()) delete text_color_;
}

void meshData_proto::ArenaDtor(void* object) {
  meshData_proto* _this = reinterpret_cast< meshData_proto* >(object);
  (void)_this;
}
void meshData_proto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void meshData_proto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void meshData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:meshData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      pversion_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      pmeshname_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(vbo_vert_ != nullptr);
      vbo_vert_->Clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(vbo_norm_ != nullptr);
      vbo_norm_->Clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(vbo_uv_ != nullptr);
      vbo_uv_->Clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(vbo_index_ != nullptr);
      vbo_index_->Clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(vbo_color_ != nullptr);
      vbo_color_->Clear();
    }
    if (cached_has_bits & 0x00000080u) {
      GOOGLE_DCHECK(vbo_weights_ != nullptr);
      vbo_weights_->Clear();
    }
  }
  if (cached_has_bits & 0x00000700u) {
    if (cached_has_bits & 0x00000100u) {
      GOOGLE_DCHECK(vbo_joints_ != nullptr);
      vbo_joints_->Clear();
    }
    if (cached_has_bits & 0x00000200u) {
      GOOGLE_DCHECK(vbo_invbind_ != nullptr);
      vbo_invbind_->Clear();
    }
    if (cached_has_bits & 0x00000400u) {
      GOOGLE_DCHECK(text_color_ != nullptr);
      text_color_->Clear();
    }
  }
  if (cached_has_bits & 0x00003800u) {
    ::memset(&mode_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&vertcount_) -
        reinterpret_cast<char*>(&mode_)) + sizeof(vertcount_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* meshData_proto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional bytes pVersion = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_pversion();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes pMeshName = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_pmeshname();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .meshData_proto.RENDER_MODE mode = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_mode(static_cast<::meshData_proto_RENDER_MODE>(val));
        } else goto handle_unusual;
        continue;
      // optional uint32 triCount = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          _Internal::set_has_tricount(&has_bits);
          tricount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 vertCount = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          _Internal::set_has_vertcount(&has_bits);
          vertcount_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_vert = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_vert(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_norm = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_norm(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_uv = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_uv(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_index = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_index(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_color = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_color(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_weights = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_weights(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_joints = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_joints(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .vboData_proto vbo_invBind = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ctx->ParseMessage(_internal_mutable_vbo_invbind(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto text_color = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ctx->ParseMessage(_internal_mutable_text_color(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* meshData_proto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:meshData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // optional bytes pVersion = 1;
  if (_internal_has_pversion()) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_pversion(), target);
  }

  // optional bytes pMeshName = 2;
  if (_internal_has_pmeshname()) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_pmeshname(), target);
  }

  // optional .meshData_proto.RENDER_MODE mode = 3;
  if (_internal_has_mode()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_mode(), target);
  }

  // optional uint32 triCount = 4;
  if (_internal_has_tricount()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(4, this->_internal_tricount(), target);
  }

  // optional uint32 vertCount = 5;
  if (_internal_has_vertcount()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(5, this->_internal_vertcount(), target);
  }

  // optional .vboData_proto vbo_vert = 6;
  if (_internal_has_vbo_vert()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::vbo_vert(this), target, stream);
  }

  // optional .vboData_proto vbo_norm = 7;
  if (_internal_has_vbo_norm()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        7, _Internal::vbo_norm(this), target, stream);
  }

  // optional .vboData_proto vbo_uv = 8;
  if (_internal_has_vbo_uv()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        8, _Internal::vbo_uv(this), target, stream);
  }

  // optional .vboData_proto vbo_index = 9;
  if (_internal_has_vbo_index()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        9, _Internal::vbo_index(this), target, stream);
  }

  // optional .vboData_proto vbo_color = 10;
  if (_internal_has_vbo_color()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        10, _Internal::vbo_color(this), target, stream);
  }

  // optional .vboData_proto vbo_weights = 11;
  if (_internal_has_vbo_weights()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        11, _Internal::vbo_weights(this), target, stream);
  }

  // optional .vboData_proto vbo_joints = 12;
  if (_internal_has_vbo_joints()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        12, _Internal::vbo_joints(this), target, stream);
  }

  // optional .vboData_proto vbo_invBind = 13;
  if (_internal_has_vbo_invbind()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        13, _Internal::vbo_invbind(this), target, stream);
  }

  // optional .textureData_proto text_color = 14;
  if (_internal_has_text_color()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        14, _Internal::text_color(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meshData_proto)
  return target;
}

size_t meshData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:meshData_proto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes pVersion = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_pversion());
    }

    // optional bytes pMeshName = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_pmeshname());
    }

    // optional .vboData_proto vbo_vert = 6;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_vert_);
    }

    // optional .vboData_proto vbo_norm = 7;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_norm_);
    }

    // optional .vboData_proto vbo_uv = 8;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_uv_);
    }

    // optional .vboData_proto vbo_index = 9;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_index_);
    }

    // optional .vboData_proto vbo_color = 10;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_color_);
    }

    // optional .vboData_proto vbo_weights = 11;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_weights_);
    }

  }
  if (cached_has_bits & 0x00003f00u) {
    // optional .vboData_proto vbo_joints = 12;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_joints_);
    }

    // optional .vboData_proto vbo_invBind = 13;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *vbo_invbind_);
    }

    // optional .textureData_proto text_color = 14;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *text_color_);
    }

    // optional .meshData_proto.RENDER_MODE mode = 3;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_mode());
    }

    // optional uint32 triCount = 4;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_tricount());
    }

    // optional uint32 vertCount = 5;
    if (cached_has_bits & 0x00002000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_vertcount());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void meshData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const meshData_proto*>(
      &from));
}

void meshData_proto::MergeFrom(const meshData_proto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:meshData_proto)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_pversion(from._internal_pversion());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_pmeshname(from._internal_pmeshname());
    }
    if (cached_has_bits & 0x00000004u) {
      _internal_mutable_vbo_vert()->::vboData_proto::MergeFrom(from._internal_vbo_vert());
    }
    if (cached_has_bits & 0x00000008u) {
      _internal_mutable_vbo_norm()->::vboData_proto::MergeFrom(from._internal_vbo_norm());
    }
    if (cached_has_bits & 0x00000010u) {
      _internal_mutable_vbo_uv()->::vboData_proto::MergeFrom(from._internal_vbo_uv());
    }
    if (cached_has_bits & 0x00000020u) {
      _internal_mutable_vbo_index()->::vboData_proto::MergeFrom(from._internal_vbo_index());
    }
    if (cached_has_bits & 0x00000040u) {
      _internal_mutable_vbo_color()->::vboData_proto::MergeFrom(from._internal_vbo_color());
    }
    if (cached_has_bits & 0x00000080u) {
      _internal_mutable_vbo_weights()->::vboData_proto::MergeFrom(from._internal_vbo_weights());
    }
  }
  if (cached_has_bits & 0x00003f00u) {
    if (cached_has_bits & 0x00000100u) {
      _internal_mutable_vbo_joints()->::vboData_proto::MergeFrom(from._internal_vbo_joints());
    }
    if (cached_has_bits & 0x00000200u) {
      _internal_mutable_vbo_invbind()->::vboData_proto::MergeFrom(from._internal_vbo_invbind());
    }
    if (cached_has_bits & 0x00000400u) {
      _internal_mutable_text_color()->::textureData_proto::MergeFrom(from._internal_text_color());
    }
    if (cached_has_bits & 0x00000800u) {
      mode_ = from.mode_;
    }
    if (cached_has_bits & 0x00001000u) {
      tricount_ = from.tricount_;
    }
    if (cached_has_bits & 0x00002000u) {
      vertcount_ = from.vertcount_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void meshData_proto::CopyFrom(const meshData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meshData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool meshData_proto::IsInitialized() const {
  return true;
}

void meshData_proto::InternalSwap(meshData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &pversion_, GetArenaForAllocation(),
      &other->pversion_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &pmeshname_, GetArenaForAllocation(),
      &other->pmeshname_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(meshData_proto, vertcount_)
      + sizeof(meshData_proto::vertcount_)
      - PROTOBUF_FIELD_OFFSET(meshData_proto, vbo_vert_)>(
          reinterpret_cast<char*>(&vbo_vert_),
          reinterpret_cast<char*>(&other->vbo_vert_));
}

std::string meshData_proto::GetTypeName() const {
  return "meshData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::meshData_proto* Arena::CreateMaybeMessage< ::meshData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::meshData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
