// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meshData.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include "vboData.pb.h"
#include "textureData.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_meshData_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_meshData_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
class meshData_proto;
struct meshData_protoDefaultTypeInternal;
extern meshData_protoDefaultTypeInternal _meshData_proto_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::meshData_proto* Arena::CreateMaybeMessage<::meshData_proto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum meshData_proto_RENDER_MODE : int {
  meshData_proto_RENDER_MODE_MODE_POINTS = 0,
  meshData_proto_RENDER_MODE_MODE_LINE = 1,
  meshData_proto_RENDER_MODE_MODE_LINE_LOOP = 2,
  meshData_proto_RENDER_MODE_MODE_LINE_STRIP = 3,
  meshData_proto_RENDER_MODE_MODE_TRIANGLES = 4,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP = 5,
  meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN = 6,
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  meshData_proto_RENDER_MODE_meshData_proto_RENDER_MODE_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool meshData_proto_RENDER_MODE_IsValid(int value);
constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MIN = meshData_proto_RENDER_MODE_MODE_POINTS;
constexpr meshData_proto_RENDER_MODE meshData_proto_RENDER_MODE_RENDER_MODE_MAX = meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
constexpr int meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE = meshData_proto_RENDER_MODE_RENDER_MODE_MAX + 1;

const std::string& meshData_proto_RENDER_MODE_Name(meshData_proto_RENDER_MODE value);
template<typename T>
inline const std::string& meshData_proto_RENDER_MODE_Name(T enum_t_value) {
  static_assert(::std::is_same<T, meshData_proto_RENDER_MODE>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function meshData_proto_RENDER_MODE_Name.");
  return meshData_proto_RENDER_MODE_Name(static_cast<meshData_proto_RENDER_MODE>(enum_t_value));
}
bool meshData_proto_RENDER_MODE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, meshData_proto_RENDER_MODE* value);
// ===================================================================

class meshData_proto final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:meshData_proto) */ {
 public:
  inline meshData_proto() : meshData_proto(nullptr) {}
  ~meshData_proto() override;
  explicit constexpr meshData_proto(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  meshData_proto(const meshData_proto& from);
  meshData_proto(meshData_proto&& from) noexcept
    : meshData_proto() {
    *this = ::std::move(from);
  }

  inline meshData_proto& operator=(const meshData_proto& from) {
    CopyFrom(from);
    return *this;
  }
  inline meshData_proto& operator=(meshData_proto&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const meshData_proto& default_instance() {
    return *internal_default_instance();
  }
  static inline const meshData_proto* internal_default_instance() {
    return reinterpret_cast<const meshData_proto*>(
               &_meshData_proto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(meshData_proto& a, meshData_proto& b) {
    a.Swap(&b);
  }
  inline void Swap(meshData_proto* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(meshData_proto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline meshData_proto* New() const final {
    return new meshData_proto();
  }

  meshData_proto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<meshData_proto>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const meshData_proto& from);
  void MergeFrom(const meshData_proto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(meshData_proto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "meshData_proto";
  }
  protected:
  explicit meshData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef meshData_proto_RENDER_MODE RENDER_MODE;
  static constexpr RENDER_MODE MODE_POINTS =
    meshData_proto_RENDER_MODE_MODE_POINTS;
  static constexpr RENDER_MODE MODE_LINE =
    meshData_proto_RENDER_MODE_MODE_LINE;
  static constexpr RENDER_MODE MODE_LINE_LOOP =
    meshData_proto_RENDER_MODE_MODE_LINE_LOOP;
  static constexpr RENDER_MODE MODE_LINE_STRIP =
    meshData_proto_RENDER_MODE_MODE_LINE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLES =
    meshData_proto_RENDER_MODE_MODE_TRIANGLES;
  static constexpr RENDER_MODE MODE_TRIANGLE_STRIP =
    meshData_proto_RENDER_MODE_MODE_TRIANGLE_STRIP;
  static constexpr RENDER_MODE MODE_TRIANGLE_FAN =
    meshData_proto_RENDER_MODE_MODE_TRIANGLE_FAN;
  static inline bool RENDER_MODE_IsValid(int value) {
    return meshData_proto_RENDER_MODE_IsValid(value);
  }
  static constexpr RENDER_MODE RENDER_MODE_MIN =
    meshData_proto_RENDER_MODE_RENDER_MODE_MIN;
  static constexpr RENDER_MODE RENDER_MODE_MAX =
    meshData_proto_RENDER_MODE_RENDER_MODE_MAX;
  static constexpr int RENDER_MODE_ARRAYSIZE =
    meshData_proto_RENDER_MODE_RENDER_MODE_ARRAYSIZE;
  template<typename T>
  static inline const std::string& RENDER_MODE_Name(T enum_t_value) {
    static_assert(::std::is_same<T, RENDER_MODE>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function RENDER_MODE_Name.");
    return meshData_proto_RENDER_MODE_Name(enum_t_value);
  }
  static inline bool RENDER_MODE_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      RENDER_MODE* value) {
    return meshData_proto_RENDER_MODE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPVersionFieldNumber = 1,
    kPMeshNameFieldNumber = 2,
    kVboVertFieldNumber = 6,
    kVboNormFieldNumber = 7,
    kVboUvFieldNumber = 8,
    kVboIndexFieldNumber = 9,
    kVboColorFieldNumber = 10,
    kVboWeightsFieldNumber = 11,
    kVboJointsFieldNumber = 12,
    kVboInvBindFieldNumber = 13,
    kTextColorFieldNumber = 14,
    kModeFieldNumber = 3,
    kTriCountFieldNumber = 4,
    kVertCountFieldNumber = 5,
  };
  // optional bytes pVersion = 1;
  bool has_pversion() const;
  private:
  bool _internal_has_pversion() const;
  public:
  void clear_pversion();
  const std::string& pversion() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pversion(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pversion();
  PROTOBUF_MUST_USE_RESULT std::string* release_pversion();
  void set_allocated_pversion(std::string* pversion);
  private:
  const std::string& _internal_pversion() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pversion(const std::string& value);
  std::string* _internal_mutable_pversion();
  public:

  // optional bytes pMeshName = 2;
  bool has_pmeshname() const;
  private:
  bool _internal_has_pmeshname() const;
  public:
  void clear_pmeshname();
  const std::string& pmeshname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_pmeshname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_pmeshname();
  PROTOBUF_MUST_USE_RESULT std::string* release_pmeshname();
  void set_allocated_pmeshname(std::string* pmeshname);
  private:
  const std::string& _internal_pmeshname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_pmeshname(const std::string& value);
  std::string* _internal_mutable_pmeshname();
  public:

  // optional .vboData_proto vbo_vert = 6;
  bool has_vbo_vert() const;
  private:
  bool _internal_has_vbo_vert() const;
  public:
  void clear_vbo_vert();
  const ::vboData_proto& vbo_vert() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_vert();
  ::vboData_proto* mutable_vbo_vert();
  void set_allocated_vbo_vert(::vboData_proto* vbo_vert);
  private:
  const ::vboData_proto& _internal_vbo_vert() const;
  ::vboData_proto* _internal_mutable_vbo_vert();
  public:
  void unsafe_arena_set_allocated_vbo_vert(
      ::vboData_proto* vbo_vert);
  ::vboData_proto* unsafe_arena_release_vbo_vert();

  // optional .vboData_proto vbo_norm = 7;
  bool has_vbo_norm() const;
  private:
  bool _internal_has_vbo_norm() const;
  public:
  void clear_vbo_norm();
  const ::vboData_proto& vbo_norm() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_norm();
  ::vboData_proto* mutable_vbo_norm();
  void set_allocated_vbo_norm(::vboData_proto* vbo_norm);
  private:
  const ::vboData_proto& _internal_vbo_norm() const;
  ::vboData_proto* _internal_mutable_vbo_norm();
  public:
  void unsafe_arena_set_allocated_vbo_norm(
      ::vboData_proto* vbo_norm);
  ::vboData_proto* unsafe_arena_release_vbo_norm();

  // optional .vboData_proto vbo_uv = 8;
  bool has_vbo_uv() const;
  private:
  bool _internal_has_vbo_uv() const;
  public:
  void clear_vbo_uv();
  const ::vboData_proto& vbo_uv() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_uv();
  ::vboData_proto* mutable_vbo_uv();
  void set_allocated_vbo_uv(::vboData_proto* vbo_uv);
  private:
  const ::vboData_proto& _internal_vbo_uv() const;
  ::vboData_proto* _internal_mutable_vbo_uv();
  public:
  void unsafe_arena_set_allocated_vbo_uv(
      ::vboData_proto* vbo_uv);
  ::vboData_proto* unsafe_arena_release_vbo_uv();

  // optional .vboData_proto vbo_index = 9;
  bool has_vbo_index() const;
  private:
  bool _internal_has_vbo_index() const;
  public:
  void clear_vbo_index();
  const ::vboData_proto& vbo_index() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_index();
  ::vboData_proto* mutable_vbo_index();
  void set_allocated_vbo_index(::vboData_proto* vbo_index);
  private:
  const ::vboData_proto& _internal_vbo_index() const;
  ::vboData_proto* _internal_mutable_vbo_index();
  public:
  void unsafe_arena_set_allocated_vbo_index(
      ::vboData_proto* vbo_index);
  ::vboData_proto* unsafe_arena_release_vbo_index();

  // optional .vboData_proto vbo_color = 10;
  bool has_vbo_color() const;
  private:
  bool _internal_has_vbo_color() const;
  public:
  void clear_vbo_color();
  const ::vboData_proto& vbo_color() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_color();
  ::vboData_proto* mutable_vbo_color();
  void set_allocated_vbo_color(::vboData_proto* vbo_color);
  private:
  const ::vboData_proto& _internal_vbo_color() const;
  ::vboData_proto* _internal_mutable_vbo_color();
  public:
  void unsafe_arena_set_allocated_vbo_color(
      ::vboData_proto* vbo_color);
  ::vboData_proto* unsafe_arena_release_vbo_color();

  // optional .vboData_proto vbo_weights = 11;
  bool has_vbo_weights() const;
  private:
  bool _internal_has_vbo_weights() const;
  public:
  void clear_vbo_weights();
  const ::vboData_proto& vbo_weights() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_weights();
  ::vboData_proto* mutable_vbo_weights();
  void set_allocated_vbo_weights(::vboData_proto* vbo_weights);
  private:
  const ::vboData_proto& _internal_vbo_weights() const;
  ::vboData_proto* _internal_mutable_vbo_weights();
  public:
  void unsafe_arena_set_allocated_vbo_weights(
      ::vboData_proto* vbo_weights);
  ::vboData_proto* unsafe_arena_release_vbo_weights();

  // optional .vboData_proto vbo_joints = 12;
  bool has_vbo_joints() const;
  private:
  bool _internal_has_vbo_joints() const;
  public:
  void clear_vbo_joints();
  const ::vboData_proto& vbo_joints() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_joints();
  ::vboData_proto* mutable_vbo_joints();
  void set_allocated_vbo_joints(::vboData_proto* vbo_joints);
  private:
  const ::vboData_proto& _internal_vbo_joints() const;
  ::vboData_proto* _internal_mutable_vbo_joints();
  public:
  void unsafe_arena_set_allocated_vbo_joints(
      ::vboData_proto* vbo_joints);
  ::vboData_proto* unsafe_arena_release_vbo_joints();

  // optional .vboData_proto vbo_invBind = 13;
  bool has_vbo_invbind() const;
  private:
  bool _internal_has_vbo_invbind() const;
  public:
  void clear_vbo_invbind();
  const ::vboData_proto& vbo_invbind() const;
  PROTOBUF_MUST_USE_RESULT ::vboData_proto* release_vbo_invbind();
  ::vboData_proto* mutable_vbo_invbind();
  void set_allocated_vbo_invbind(::vboData_proto* vbo_invbind);
  private:
  const ::vboData_proto& _internal_vbo_invbind() const;
  ::vboData_proto* _internal_mutable_vbo_invbind();
  public:
  void unsafe_arena_set_allocated_vbo_invbind(
      ::vboData_proto* vbo_invbind);
  ::vboData_proto* unsafe_arena_release_vbo_invbind();

  // optional .textureData_proto text_color = 14;
  bool has_text_color() const;
  private:
  bool _internal_has_text_color() const;
  public:
  void clear_text_color();
  const ::textureData_proto& text_color() const;
  PROTOBUF_MUST_USE_RESULT ::textureData_proto* release_text_color();
  ::textureData_proto* mutable_text_color();
  void set_allocated_text_color(::textureData_proto* text_color);
  private:
  const ::textureData_proto& _internal_text_color() const;
  ::textureData_proto* _internal_mutable_text_color();
  public:
  void unsafe_arena_set_allocated_text_color(
      ::textureData_proto* text_color);
  ::textureData_proto* unsafe_arena_release_text_color();

  // optional .meshData_proto.RENDER_MODE mode = 3;
  bool has_mode() const;
  private:
  bool _internal_has_mode() const;
  public:
  void clear_mode();
  ::meshData_proto_RENDER_MODE mode() const;
  void set_mode(::meshData_proto_RENDER_MODE value);
  private:
  ::meshData_proto_RENDER_MODE _internal_mode() const;
  void _internal_set_mode(::meshData_proto_RENDER_MODE value);
  public:

  // optional uint32 triCount = 4;
  bool has_tricount() const;
  private:
  bool _internal_has_tricount() const;
  public:
  void clear_tricount();
  ::PROTOBUF_NAMESPACE_ID::uint32 tricount() const;
  void set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_tricount() const;
  void _internal_set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 vertCount = 5;
  bool has_vertcount() const;
  private:
  bool _internal_has_vertcount() const;
  public:
  void clear_vertcount();
  ::PROTOBUF_NAMESPACE_ID::uint32 vertcount() const;
  void set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_vertcount() const;
  void _internal_set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:meshData_proto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pversion_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pmeshname_;
  ::vboData_proto* vbo_vert_;
  ::vboData_proto* vbo_norm_;
  ::vboData_proto* vbo_uv_;
  ::vboData_proto* vbo_index_;
  ::vboData_proto* vbo_color_;
  ::vboData_proto* vbo_weights_;
  ::vboData_proto* vbo_joints_;
  ::vboData_proto* vbo_invbind_;
  ::textureData_proto* text_color_;
  int mode_;
  ::PROTOBUF_NAMESPACE_ID::uint32 tricount_;
  ::PROTOBUF_NAMESPACE_ID::uint32 vertcount_;
  friend struct ::TableStruct_meshData_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// meshData_proto

// optional bytes pVersion = 1;
inline bool meshData_proto::_internal_has_pversion() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool meshData_proto::has_pversion() const {
  return _internal_has_pversion();
}
inline void meshData_proto::clear_pversion() {
  pversion_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& meshData_proto::pversion() const {
  // @@protoc_insertion_point(field_get:meshData_proto.pVersion)
  return _internal_pversion();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void meshData_proto::set_pversion(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 pversion_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meshData_proto.pVersion)
}
inline std::string* meshData_proto::mutable_pversion() {
  std::string* _s = _internal_mutable_pversion();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pVersion)
  return _s;
}
inline const std::string& meshData_proto::_internal_pversion() const {
  return pversion_.Get();
}
inline void meshData_proto::_internal_set_pversion(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  pversion_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* meshData_proto::_internal_mutable_pversion() {
  _has_bits_[0] |= 0x00000001u;
  return pversion_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* meshData_proto::release_pversion() {
  // @@protoc_insertion_point(field_release:meshData_proto.pVersion)
  if (!_internal_has_pversion()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return pversion_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void meshData_proto::set_allocated_pversion(std::string* pversion) {
  if (pversion != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  pversion_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pversion,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pVersion)
}

// optional bytes pMeshName = 2;
inline bool meshData_proto::_internal_has_pmeshname() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool meshData_proto::has_pmeshname() const {
  return _internal_has_pmeshname();
}
inline void meshData_proto::clear_pmeshname() {
  pmeshname_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& meshData_proto::pmeshname() const {
  // @@protoc_insertion_point(field_get:meshData_proto.pMeshName)
  return _internal_pmeshname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void meshData_proto::set_pmeshname(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 pmeshname_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:meshData_proto.pMeshName)
}
inline std::string* meshData_proto::mutable_pmeshname() {
  std::string* _s = _internal_mutable_pmeshname();
  // @@protoc_insertion_point(field_mutable:meshData_proto.pMeshName)
  return _s;
}
inline const std::string& meshData_proto::_internal_pmeshname() const {
  return pmeshname_.Get();
}
inline void meshData_proto::_internal_set_pmeshname(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  pmeshname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* meshData_proto::_internal_mutable_pmeshname() {
  _has_bits_[0] |= 0x00000002u;
  return pmeshname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* meshData_proto::release_pmeshname() {
  // @@protoc_insertion_point(field_release:meshData_proto.pMeshName)
  if (!_internal_has_pmeshname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return pmeshname_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void meshData_proto::set_allocated_pmeshname(std::string* pmeshname) {
  if (pmeshname != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  pmeshname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pmeshname,
      GetArenaForAllocation());
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.pMeshName)
}

// optional .meshData_proto.RENDER_MODE mode = 3;
inline bool meshData_proto::_internal_has_mode() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool meshData_proto::has_mode() const {
  return _internal_has_mode();
}
inline void meshData_proto::clear_mode() {
  mode_ = 0;
  _has_bits_[0] &= ~0x00000800u;
}
inline ::meshData_proto_RENDER_MODE meshData_proto::_internal_mode() const {
  return static_cast< ::meshData_proto_RENDER_MODE >(mode_);
}
inline ::meshData_proto_RENDER_MODE meshData_proto::mode() const {
  // @@protoc_insertion_point(field_get:meshData_proto.mode)
  return _internal_mode();
}
inline void meshData_proto::_internal_set_mode(::meshData_proto_RENDER_MODE value) {
  _has_bits_[0] |= 0x00000800u;
  mode_ = value;
}
inline void meshData_proto::set_mode(::meshData_proto_RENDER_MODE value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:meshData_proto.mode)
}

// optional uint32 triCount = 4;
inline bool meshData_proto::_internal_has_tricount() const {
  bool value = (_has_bits_[0] & 0x00001000u) != 0;
  return value;
}
inline bool meshData_proto::has_tricount() const {
  return _internal_has_tricount();
}
inline void meshData_proto::clear_tricount() {
  tricount_ = 0u;
  _has_bits_[0] &= ~0x00001000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::_internal_tricount() const {
  return tricount_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::tricount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.triCount)
  return _internal_tricount();
}
inline void meshData_proto::_internal_set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00001000u;
  tricount_ = value;
}
inline void meshData_proto::set_tricount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_tricount(value);
  // @@protoc_insertion_point(field_set:meshData_proto.triCount)
}

// optional uint32 vertCount = 5;
inline bool meshData_proto::_internal_has_vertcount() const {
  bool value = (_has_bits_[0] & 0x00002000u) != 0;
  return value;
}
inline bool meshData_proto::has_vertcount() const {
  return _internal_has_vertcount();
}
inline void meshData_proto::clear_vertcount() {
  vertcount_ = 0u;
  _has_bits_[0] &= ~0x00002000u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::_internal_vertcount() const {
  return vertcount_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 meshData_proto::vertcount() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vertCount)
  return _internal_vertcount();
}
inline void meshData_proto::_internal_set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00002000u;
  vertcount_ = value;
}
inline void meshData_proto::set_vertcount(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_vertcount(value);
  // @@protoc_insertion_point(field_set:meshData_proto.vertCount)
}

// optional .vboData_proto vbo_vert = 6;
inline bool meshData_proto::_internal_has_vbo_vert() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || vbo_vert_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_vert() const {
  return _internal_has_vbo_vert();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_vert() const {
  const ::vboData_proto* p = vbo_vert_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_vert() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_vert)
  return _internal_vbo_vert();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_vert(
    ::vboData_proto* vbo_vert) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert_);
  }
  vbo_vert_ = vbo_vert;
  if (vbo_vert) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_vert)
}
inline ::vboData_proto* meshData_proto::release_vbo_vert() {
  _has_bits_[0] &= ~0x00000004u;
  ::vboData_proto* temp = vbo_vert_;
  vbo_vert_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_vert() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_vert)
  _has_bits_[0] &= ~0x00000004u;
  ::vboData_proto* temp = vbo_vert_;
  vbo_vert_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_vert() {
  _has_bits_[0] |= 0x00000004u;
  if (vbo_vert_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_vert_ = p;
  }
  return vbo_vert_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_vert() {
  ::vboData_proto* _msg = _internal_mutable_vbo_vert();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_vert)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_vert(::vboData_proto* vbo_vert) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert_);
  }
  if (vbo_vert) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_vert));
    if (message_arena != submessage_arena) {
      vbo_vert = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_vert, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  vbo_vert_ = vbo_vert;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_vert)
}

// optional .vboData_proto vbo_norm = 7;
inline bool meshData_proto::_internal_has_vbo_norm() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || vbo_norm_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_norm() const {
  return _internal_has_vbo_norm();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_norm() const {
  const ::vboData_proto* p = vbo_norm_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_norm() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_norm)
  return _internal_vbo_norm();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_norm(
    ::vboData_proto* vbo_norm) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm_);
  }
  vbo_norm_ = vbo_norm;
  if (vbo_norm) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_norm)
}
inline ::vboData_proto* meshData_proto::release_vbo_norm() {
  _has_bits_[0] &= ~0x00000008u;
  ::vboData_proto* temp = vbo_norm_;
  vbo_norm_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_norm() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_norm)
  _has_bits_[0] &= ~0x00000008u;
  ::vboData_proto* temp = vbo_norm_;
  vbo_norm_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_norm() {
  _has_bits_[0] |= 0x00000008u;
  if (vbo_norm_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_norm_ = p;
  }
  return vbo_norm_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_norm() {
  ::vboData_proto* _msg = _internal_mutable_vbo_norm();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_norm)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_norm(::vboData_proto* vbo_norm) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm_);
  }
  if (vbo_norm) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_norm));
    if (message_arena != submessage_arena) {
      vbo_norm = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_norm, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  vbo_norm_ = vbo_norm;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_norm)
}

// optional .vboData_proto vbo_uv = 8;
inline bool meshData_proto::_internal_has_vbo_uv() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || vbo_uv_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_uv() const {
  return _internal_has_vbo_uv();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_uv() const {
  const ::vboData_proto* p = vbo_uv_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_uv() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_uv)
  return _internal_vbo_uv();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_uv(
    ::vboData_proto* vbo_uv) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv_);
  }
  vbo_uv_ = vbo_uv;
  if (vbo_uv) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_uv)
}
inline ::vboData_proto* meshData_proto::release_vbo_uv() {
  _has_bits_[0] &= ~0x00000010u;
  ::vboData_proto* temp = vbo_uv_;
  vbo_uv_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_uv() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_uv)
  _has_bits_[0] &= ~0x00000010u;
  ::vboData_proto* temp = vbo_uv_;
  vbo_uv_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_uv() {
  _has_bits_[0] |= 0x00000010u;
  if (vbo_uv_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_uv_ = p;
  }
  return vbo_uv_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_uv() {
  ::vboData_proto* _msg = _internal_mutable_vbo_uv();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_uv)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_uv(::vboData_proto* vbo_uv) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv_);
  }
  if (vbo_uv) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_uv));
    if (message_arena != submessage_arena) {
      vbo_uv = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_uv, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  vbo_uv_ = vbo_uv;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_uv)
}

// optional .vboData_proto vbo_index = 9;
inline bool meshData_proto::_internal_has_vbo_index() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || vbo_index_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_index() const {
  return _internal_has_vbo_index();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_index() const {
  const ::vboData_proto* p = vbo_index_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_index() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_index)
  return _internal_vbo_index();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_index(
    ::vboData_proto* vbo_index) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index_);
  }
  vbo_index_ = vbo_index;
  if (vbo_index) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_index)
}
inline ::vboData_proto* meshData_proto::release_vbo_index() {
  _has_bits_[0] &= ~0x00000020u;
  ::vboData_proto* temp = vbo_index_;
  vbo_index_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_index() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_index)
  _has_bits_[0] &= ~0x00000020u;
  ::vboData_proto* temp = vbo_index_;
  vbo_index_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_index() {
  _has_bits_[0] |= 0x00000020u;
  if (vbo_index_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_index_ = p;
  }
  return vbo_index_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_index() {
  ::vboData_proto* _msg = _internal_mutable_vbo_index();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_index)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_index(::vboData_proto* vbo_index) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index_);
  }
  if (vbo_index) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_index));
    if (message_arena != submessage_arena) {
      vbo_index = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_index, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  vbo_index_ = vbo_index;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_index)
}

// optional .vboData_proto vbo_color = 10;
inline bool meshData_proto::_internal_has_vbo_color() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  PROTOBUF_ASSUME(!value || vbo_color_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_color() const {
  return _internal_has_vbo_color();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_color() const {
  const ::vboData_proto* p = vbo_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_color() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_color)
  return _internal_vbo_color();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_color(
    ::vboData_proto* vbo_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color_);
  }
  vbo_color_ = vbo_color;
  if (vbo_color) {
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_color)
}
inline ::vboData_proto* meshData_proto::release_vbo_color() {
  _has_bits_[0] &= ~0x00000040u;
  ::vboData_proto* temp = vbo_color_;
  vbo_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_color() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_color)
  _has_bits_[0] &= ~0x00000040u;
  ::vboData_proto* temp = vbo_color_;
  vbo_color_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_color() {
  _has_bits_[0] |= 0x00000040u;
  if (vbo_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_color_ = p;
  }
  return vbo_color_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_color() {
  ::vboData_proto* _msg = _internal_mutable_vbo_color();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_color)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_color(::vboData_proto* vbo_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color_);
  }
  if (vbo_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_color));
    if (message_arena != submessage_arena) {
      vbo_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000040u;
  } else {
    _has_bits_[0] &= ~0x00000040u;
  }
  vbo_color_ = vbo_color;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_color)
}

// optional .vboData_proto vbo_weights = 11;
inline bool meshData_proto::_internal_has_vbo_weights() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  PROTOBUF_ASSUME(!value || vbo_weights_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_weights() const {
  return _internal_has_vbo_weights();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_weights() const {
  const ::vboData_proto* p = vbo_weights_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_weights() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_weights)
  return _internal_vbo_weights();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_weights(
    ::vboData_proto* vbo_weights) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_weights_);
  }
  vbo_weights_ = vbo_weights;
  if (vbo_weights) {
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_weights)
}
inline ::vboData_proto* meshData_proto::release_vbo_weights() {
  _has_bits_[0] &= ~0x00000080u;
  ::vboData_proto* temp = vbo_weights_;
  vbo_weights_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_weights() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_weights)
  _has_bits_[0] &= ~0x00000080u;
  ::vboData_proto* temp = vbo_weights_;
  vbo_weights_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_weights() {
  _has_bits_[0] |= 0x00000080u;
  if (vbo_weights_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_weights_ = p;
  }
  return vbo_weights_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_weights() {
  ::vboData_proto* _msg = _internal_mutable_vbo_weights();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_weights)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_weights(::vboData_proto* vbo_weights) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_weights_);
  }
  if (vbo_weights) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_weights));
    if (message_arena != submessage_arena) {
      vbo_weights = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_weights, submessage_arena);
    }
    _has_bits_[0] |= 0x00000080u;
  } else {
    _has_bits_[0] &= ~0x00000080u;
  }
  vbo_weights_ = vbo_weights;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_weights)
}

// optional .vboData_proto vbo_joints = 12;
inline bool meshData_proto::_internal_has_vbo_joints() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  PROTOBUF_ASSUME(!value || vbo_joints_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_joints() const {
  return _internal_has_vbo_joints();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_joints() const {
  const ::vboData_proto* p = vbo_joints_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_joints() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_joints)
  return _internal_vbo_joints();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_joints(
    ::vboData_proto* vbo_joints) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_joints_);
  }
  vbo_joints_ = vbo_joints;
  if (vbo_joints) {
    _has_bits_[0] |= 0x00000100u;
  } else {
    _has_bits_[0] &= ~0x00000100u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_joints)
}
inline ::vboData_proto* meshData_proto::release_vbo_joints() {
  _has_bits_[0] &= ~0x00000100u;
  ::vboData_proto* temp = vbo_joints_;
  vbo_joints_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_joints() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_joints)
  _has_bits_[0] &= ~0x00000100u;
  ::vboData_proto* temp = vbo_joints_;
  vbo_joints_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_joints() {
  _has_bits_[0] |= 0x00000100u;
  if (vbo_joints_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_joints_ = p;
  }
  return vbo_joints_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_joints() {
  ::vboData_proto* _msg = _internal_mutable_vbo_joints();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_joints)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_joints(::vboData_proto* vbo_joints) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_joints_);
  }
  if (vbo_joints) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_joints));
    if (message_arena != submessage_arena) {
      vbo_joints = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_joints, submessage_arena);
    }
    _has_bits_[0] |= 0x00000100u;
  } else {
    _has_bits_[0] &= ~0x00000100u;
  }
  vbo_joints_ = vbo_joints;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_joints)
}

// optional .vboData_proto vbo_invBind = 13;
inline bool meshData_proto::_internal_has_vbo_invbind() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  PROTOBUF_ASSUME(!value || vbo_invbind_ != nullptr);
  return value;
}
inline bool meshData_proto::has_vbo_invbind() const {
  return _internal_has_vbo_invbind();
}
inline const ::vboData_proto& meshData_proto::_internal_vbo_invbind() const {
  const ::vboData_proto* p = vbo_invbind_;
  return p != nullptr ? *p : reinterpret_cast<const ::vboData_proto&>(
      ::_vboData_proto_default_instance_);
}
inline const ::vboData_proto& meshData_proto::vbo_invbind() const {
  // @@protoc_insertion_point(field_get:meshData_proto.vbo_invBind)
  return _internal_vbo_invbind();
}
inline void meshData_proto::unsafe_arena_set_allocated_vbo_invbind(
    ::vboData_proto* vbo_invbind) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_invbind_);
  }
  vbo_invbind_ = vbo_invbind;
  if (vbo_invbind) {
    _has_bits_[0] |= 0x00000200u;
  } else {
    _has_bits_[0] &= ~0x00000200u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.vbo_invBind)
}
inline ::vboData_proto* meshData_proto::release_vbo_invbind() {
  _has_bits_[0] &= ~0x00000200u;
  ::vboData_proto* temp = vbo_invbind_;
  vbo_invbind_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::vboData_proto* meshData_proto::unsafe_arena_release_vbo_invbind() {
  // @@protoc_insertion_point(field_release:meshData_proto.vbo_invBind)
  _has_bits_[0] &= ~0x00000200u;
  ::vboData_proto* temp = vbo_invbind_;
  vbo_invbind_ = nullptr;
  return temp;
}
inline ::vboData_proto* meshData_proto::_internal_mutable_vbo_invbind() {
  _has_bits_[0] |= 0x00000200u;
  if (vbo_invbind_ == nullptr) {
    auto* p = CreateMaybeMessage<::vboData_proto>(GetArenaForAllocation());
    vbo_invbind_ = p;
  }
  return vbo_invbind_;
}
inline ::vboData_proto* meshData_proto::mutable_vbo_invbind() {
  ::vboData_proto* _msg = _internal_mutable_vbo_invbind();
  // @@protoc_insertion_point(field_mutable:meshData_proto.vbo_invBind)
  return _msg;
}
inline void meshData_proto::set_allocated_vbo_invbind(::vboData_proto* vbo_invbind) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_invbind_);
  }
  if (vbo_invbind) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(vbo_invbind));
    if (message_arena != submessage_arena) {
      vbo_invbind = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, vbo_invbind, submessage_arena);
    }
    _has_bits_[0] |= 0x00000200u;
  } else {
    _has_bits_[0] &= ~0x00000200u;
  }
  vbo_invbind_ = vbo_invbind;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.vbo_invBind)
}

// optional .textureData_proto text_color = 14;
inline bool meshData_proto::_internal_has_text_color() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  PROTOBUF_ASSUME(!value || text_color_ != nullptr);
  return value;
}
inline bool meshData_proto::has_text_color() const {
  return _internal_has_text_color();
}
inline const ::textureData_proto& meshData_proto::_internal_text_color() const {
  const ::textureData_proto* p = text_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::textureData_proto&>(
      ::_textureData_proto_default_instance_);
}
inline const ::textureData_proto& meshData_proto::text_color() const {
  // @@protoc_insertion_point(field_get:meshData_proto.text_color)
  return _internal_text_color();
}
inline void meshData_proto::unsafe_arena_set_allocated_text_color(
    ::textureData_proto* text_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(text_color_);
  }
  text_color_ = text_color;
  if (text_color) {
    _has_bits_[0] |= 0x00000400u;
  } else {
    _has_bits_[0] &= ~0x00000400u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:meshData_proto.text_color)
}
inline ::textureData_proto* meshData_proto::release_text_color() {
  _has_bits_[0] &= ~0x00000400u;
  ::textureData_proto* temp = text_color_;
  text_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::textureData_proto* meshData_proto::unsafe_arena_release_text_color() {
  // @@protoc_insertion_point(field_release:meshData_proto.text_color)
  _has_bits_[0] &= ~0x00000400u;
  ::textureData_proto* temp = text_color_;
  text_color_ = nullptr;
  return temp;
}
inline ::textureData_proto* meshData_proto::_internal_mutable_text_color() {
  _has_bits_[0] |= 0x00000400u;
  if (text_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::textureData_proto>(GetArenaForAllocation());
    text_color_ = p;
  }
  return text_color_;
}
inline ::textureData_proto* meshData_proto::mutable_text_color() {
  ::textureData_proto* _msg = _internal_mutable_text_color();
  // @@protoc_insertion_point(field_mutable:meshData_proto.text_color)
  return _msg;
}
inline void meshData_proto::set_allocated_text_color(::textureData_proto* text_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete static_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(text_color_);
  }
  if (text_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                static_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(text_color));
    if (message_arena != submessage_arena) {
      text_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, text_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000400u;
  } else {
    _has_bits_[0] &= ~0x00000400u;
  }
  text_color_ = text_color;
  // @@protoc_insertion_point(field_set_allocated:meshData_proto.text_color)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::meshData_proto_RENDER_MODE> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_meshData_2eproto
