// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: textureData.proto

#include "textureData.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr textureData_proto::textureData_proto(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : md5_()
  , _md5_cached_byte_size_(0)
  , filenamedata_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , podata_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , enabled_(0u)
  , texttype_(0)

  , magfilter_(0)

  , minfilter_(0)

  , wraps_(0)

  , wrapt_(0)

  , eformat_(0)

  , ncomponent_(0)

  , width_(0u)
  , height_(0u)
  , component_(0u)
  , bits_(0u)
  , as_is_(0u)
  , pixel_type_(0)

  , filenamesize_(0u)
  , datasize_(0u){}
struct textureData_protoDefaultTypeInternal {
  constexpr textureData_protoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~textureData_protoDefaultTypeInternal() {}
  union {
    textureData_proto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT textureData_protoDefaultTypeInternal _textureData_proto_default_instance_;
bool textureData_proto_TEXTURE_EFORMAT_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_EFORMAT_strings[3] = {};

static const char textureData_proto_TEXTURE_EFORMAT_names[] =
  "EFORMAT_BGR"
  "EFORMAT_RGB"
  "EFORMAT_RGBA";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_EFORMAT_entries[] = {
  { {textureData_proto_TEXTURE_EFORMAT_names + 0, 11}, 0 },
  { {textureData_proto_TEXTURE_EFORMAT_names + 11, 11}, 1 },
  { {textureData_proto_TEXTURE_EFORMAT_names + 22, 12}, 2 },
};

static const int textureData_proto_TEXTURE_EFORMAT_entries_by_number[] = {
  0, // 0 -> EFORMAT_BGR
  1, // 1 -> EFORMAT_RGB
  2, // 2 -> EFORMAT_RGBA
};

const std::string& textureData_proto_TEXTURE_EFORMAT_Name(
    textureData_proto_TEXTURE_EFORMAT value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_EFORMAT_entries,
          textureData_proto_TEXTURE_EFORMAT_entries_by_number,
          3, textureData_proto_TEXTURE_EFORMAT_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_EFORMAT_entries,
      textureData_proto_TEXTURE_EFORMAT_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_EFORMAT_strings[idx].get();
}
bool textureData_proto_TEXTURE_EFORMAT_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_EFORMAT* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_EFORMAT_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_EFORMAT>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_BGR;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_RGB;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::EFORMAT_RGBA;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::TEXTURE_EFORMAT_MIN;
constexpr textureData_proto_TEXTURE_EFORMAT textureData_proto::TEXTURE_EFORMAT_MAX;
constexpr int textureData_proto::TEXTURE_EFORMAT_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_NCOMPONENT_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_NCOMPONENT_strings[3] = {};

static const char textureData_proto_TEXTURE_NCOMPONENT_names[] =
  "NCOMPONENT_BGR"
  "NCOMPONENT_RGB"
  "NCOMPONENT_RGBA";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_NCOMPONENT_entries[] = {
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 0, 14}, 0 },
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 14, 14}, 1 },
  { {textureData_proto_TEXTURE_NCOMPONENT_names + 28, 15}, 2 },
};

static const int textureData_proto_TEXTURE_NCOMPONENT_entries_by_number[] = {
  0, // 0 -> NCOMPONENT_BGR
  1, // 1 -> NCOMPONENT_RGB
  2, // 2 -> NCOMPONENT_RGBA
};

const std::string& textureData_proto_TEXTURE_NCOMPONENT_Name(
    textureData_proto_TEXTURE_NCOMPONENT value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_NCOMPONENT_entries,
          textureData_proto_TEXTURE_NCOMPONENT_entries_by_number,
          3, textureData_proto_TEXTURE_NCOMPONENT_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_NCOMPONENT_entries,
      textureData_proto_TEXTURE_NCOMPONENT_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_NCOMPONENT_strings[idx].get();
}
bool textureData_proto_TEXTURE_NCOMPONENT_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_NCOMPONENT* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_NCOMPONENT_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_NCOMPONENT>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_BGR;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_RGB;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::NCOMPONENT_RGBA;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::TEXTURE_NCOMPONENT_MIN;
constexpr textureData_proto_TEXTURE_NCOMPONENT textureData_proto::TEXTURE_NCOMPONENT_MAX;
constexpr int textureData_proto::TEXTURE_NCOMPONENT_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_TYPE_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_TYPE_strings[5] = {};

static const char textureData_proto_TEXTURE_TYPE_names[] =
  "BMP"
  "GIF"
  "JPEG"
  "PNG"
  "TGA";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_TYPE_entries[] = {
  { {textureData_proto_TEXTURE_TYPE_names + 0, 3}, 2 },
  { {textureData_proto_TEXTURE_TYPE_names + 3, 3}, 3 },
  { {textureData_proto_TEXTURE_TYPE_names + 6, 4}, 0 },
  { {textureData_proto_TEXTURE_TYPE_names + 10, 3}, 1 },
  { {textureData_proto_TEXTURE_TYPE_names + 13, 3}, 4 },
};

static const int textureData_proto_TEXTURE_TYPE_entries_by_number[] = {
  2, // 0 -> JPEG
  3, // 1 -> PNG
  0, // 2 -> BMP
  1, // 3 -> GIF
  4, // 4 -> TGA
};

const std::string& textureData_proto_TEXTURE_TYPE_Name(
    textureData_proto_TEXTURE_TYPE value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_TYPE_entries,
          textureData_proto_TEXTURE_TYPE_entries_by_number,
          5, textureData_proto_TEXTURE_TYPE_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_TYPE_entries,
      textureData_proto_TEXTURE_TYPE_entries_by_number,
      5, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_TYPE_strings[idx].get();
}
bool textureData_proto_TEXTURE_TYPE_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_TYPE* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_TYPE_entries, 5, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_TYPE>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::JPEG;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::PNG;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::BMP;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::GIF;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::TGA;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::TEXTURE_TYPE_MIN;
constexpr textureData_proto_TEXTURE_TYPE textureData_proto::TEXTURE_TYPE_MAX;
constexpr int textureData_proto::TEXTURE_TYPE_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_MAG_FILTER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_MAG_FILTER_strings[2] = {};

static const char textureData_proto_TEXTURE_MAG_FILTER_names[] =
  "MAG_LINEAR"
  "MAG_NEAREST";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_MAG_FILTER_entries[] = {
  { {textureData_proto_TEXTURE_MAG_FILTER_names + 0, 10}, 1 },
  { {textureData_proto_TEXTURE_MAG_FILTER_names + 10, 11}, 0 },
};

static const int textureData_proto_TEXTURE_MAG_FILTER_entries_by_number[] = {
  1, // 0 -> MAG_NEAREST
  0, // 1 -> MAG_LINEAR
};

const std::string& textureData_proto_TEXTURE_MAG_FILTER_Name(
    textureData_proto_TEXTURE_MAG_FILTER value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_MAG_FILTER_entries,
          textureData_proto_TEXTURE_MAG_FILTER_entries_by_number,
          2, textureData_proto_TEXTURE_MAG_FILTER_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_MAG_FILTER_entries,
      textureData_proto_TEXTURE_MAG_FILTER_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_MAG_FILTER_strings[idx].get();
}
bool textureData_proto_TEXTURE_MAG_FILTER_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_MAG_FILTER* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_MAG_FILTER_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_MAG_FILTER>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::MAG_NEAREST;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::MAG_LINEAR;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::TEXTURE_MAG_FILTER_MIN;
constexpr textureData_proto_TEXTURE_MAG_FILTER textureData_proto::TEXTURE_MAG_FILTER_MAX;
constexpr int textureData_proto::TEXTURE_MAG_FILTER_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_MIN_FILTER_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_MIN_FILTER_strings[6] = {};

static const char textureData_proto_TEXTURE_MIN_FILTER_names[] =
  "MIN_LINEAR"
  "MIN_LINEAR_MIPMAP_LINEAR"
  "MIN_LINEAR_MIPMAP_NEAREST"
  "MIN_NEAREST"
  "MIN_NEAREST_MIPMAP_LINEAR"
  "MIN_NEAREST_MIPMAP_NEAREST";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_MIN_FILTER_entries[] = {
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 0, 10}, 1 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 10, 24}, 5 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 34, 25}, 3 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 59, 11}, 0 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 70, 25}, 4 },
  { {textureData_proto_TEXTURE_MIN_FILTER_names + 95, 26}, 2 },
};

static const int textureData_proto_TEXTURE_MIN_FILTER_entries_by_number[] = {
  3, // 0 -> MIN_NEAREST
  0, // 1 -> MIN_LINEAR
  5, // 2 -> MIN_NEAREST_MIPMAP_NEAREST
  2, // 3 -> MIN_LINEAR_MIPMAP_NEAREST
  4, // 4 -> MIN_NEAREST_MIPMAP_LINEAR
  1, // 5 -> MIN_LINEAR_MIPMAP_LINEAR
};

const std::string& textureData_proto_TEXTURE_MIN_FILTER_Name(
    textureData_proto_TEXTURE_MIN_FILTER value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_MIN_FILTER_entries,
          textureData_proto_TEXTURE_MIN_FILTER_entries_by_number,
          6, textureData_proto_TEXTURE_MIN_FILTER_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_MIN_FILTER_entries,
      textureData_proto_TEXTURE_MIN_FILTER_entries_by_number,
      6, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_MIN_FILTER_strings[idx].get();
}
bool textureData_proto_TEXTURE_MIN_FILTER_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_MIN_FILTER* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_MIN_FILTER_entries, 6, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_MIN_FILTER>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST_MIPMAP_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR_MIPMAP_NEAREST;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_NEAREST_MIPMAP_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::MIN_LINEAR_MIPMAP_LINEAR;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::TEXTURE_MIN_FILTER_MIN;
constexpr textureData_proto_TEXTURE_MIN_FILTER textureData_proto::TEXTURE_MIN_FILTER_MAX;
constexpr int textureData_proto::TEXTURE_MIN_FILTER_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_WRAP_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_WRAP_strings[3] = {};

static const char textureData_proto_TEXTURE_WRAP_names[] =
  "WRAP_CLAMP_TO_EDGE"
  "WRAP_MIRRORED_REPEAT"
  "WRAP_REPEAT";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_WRAP_entries[] = {
  { {textureData_proto_TEXTURE_WRAP_names + 0, 18}, 0 },
  { {textureData_proto_TEXTURE_WRAP_names + 18, 20}, 1 },
  { {textureData_proto_TEXTURE_WRAP_names + 38, 11}, 2 },
};

static const int textureData_proto_TEXTURE_WRAP_entries_by_number[] = {
  0, // 0 -> WRAP_CLAMP_TO_EDGE
  1, // 1 -> WRAP_MIRRORED_REPEAT
  2, // 2 -> WRAP_REPEAT
};

const std::string& textureData_proto_TEXTURE_WRAP_Name(
    textureData_proto_TEXTURE_WRAP value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_WRAP_entries,
          textureData_proto_TEXTURE_WRAP_entries_by_number,
          3, textureData_proto_TEXTURE_WRAP_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_WRAP_entries,
      textureData_proto_TEXTURE_WRAP_entries_by_number,
      3, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_WRAP_strings[idx].get();
}
bool textureData_proto_TEXTURE_WRAP_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_WRAP* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_WRAP_entries, 3, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_WRAP>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_CLAMP_TO_EDGE;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_MIRRORED_REPEAT;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::WRAP_REPEAT;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::TEXTURE_WRAP_MIN;
constexpr textureData_proto_TEXTURE_WRAP textureData_proto::TEXTURE_WRAP_MAX;
constexpr int textureData_proto::TEXTURE_WRAP_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
bool textureData_proto_TEXTURE_COMPONENT_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> textureData_proto_TEXTURE_COMPONENT_strings[8] = {};

static const char textureData_proto_TEXTURE_COMPONENT_names[] =
  "BYTE"
  "DOUBLE"
  "FLOAT"
  "INT"
  "SHORT"
  "UNSIGNED_BYTE"
  "UNSIGNED_INT"
  "UNSIGNED_SHORT";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry textureData_proto_TEXTURE_COMPONENT_entries[] = {
  { {textureData_proto_TEXTURE_COMPONENT_names + 0, 4}, 0 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 4, 6}, 7 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 10, 5}, 6 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 15, 3}, 4 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 18, 5}, 2 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 23, 13}, 1 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 36, 12}, 5 },
  { {textureData_proto_TEXTURE_COMPONENT_names + 48, 14}, 3 },
};

static const int textureData_proto_TEXTURE_COMPONENT_entries_by_number[] = {
  0, // 0 -> BYTE
  5, // 1 -> UNSIGNED_BYTE
  4, // 2 -> SHORT
  7, // 3 -> UNSIGNED_SHORT
  3, // 4 -> INT
  6, // 5 -> UNSIGNED_INT
  2, // 6 -> FLOAT
  1, // 7 -> DOUBLE
};

const std::string& textureData_proto_TEXTURE_COMPONENT_Name(
    textureData_proto_TEXTURE_COMPONENT value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          textureData_proto_TEXTURE_COMPONENT_entries,
          textureData_proto_TEXTURE_COMPONENT_entries_by_number,
          8, textureData_proto_TEXTURE_COMPONENT_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      textureData_proto_TEXTURE_COMPONENT_entries,
      textureData_proto_TEXTURE_COMPONENT_entries_by_number,
      8, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     textureData_proto_TEXTURE_COMPONENT_strings[idx].get();
}
bool textureData_proto_TEXTURE_COMPONENT_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, textureData_proto_TEXTURE_COMPONENT* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      textureData_proto_TEXTURE_COMPONENT_entries, 8, name, &int_value);
  if (success) {
    *value = static_cast<textureData_proto_TEXTURE_COMPONENT>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::BYTE;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::UNSIGNED_BYTE;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::SHORT;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::UNSIGNED_SHORT;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::INT;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::UNSIGNED_INT;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::FLOAT;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::DOUBLE;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::TEXTURE_COMPONENT_MIN;
constexpr textureData_proto_TEXTURE_COMPONENT textureData_proto::TEXTURE_COMPONENT_MAX;
constexpr int textureData_proto::TEXTURE_COMPONENT_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

class textureData_proto::_Internal {
 public:
  using HasBits = decltype(std::declval<textureData_proto>()._has_bits_);
  static void set_has_enabled(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_texttype(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_magfilter(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static void set_has_minfilter(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_wraps(HasBits* has_bits) {
    (*has_bits)[0] |= 64u;
  }
  static void set_has_wrapt(HasBits* has_bits) {
    (*has_bits)[0] |= 128u;
  }
  static void set_has_eformat(HasBits* has_bits) {
    (*has_bits)[0] |= 256u;
  }
  static void set_has_ncomponent(HasBits* has_bits) {
    (*has_bits)[0] |= 512u;
  }
  static void set_has_width(HasBits* has_bits) {
    (*has_bits)[0] |= 1024u;
  }
  static void set_has_height(HasBits* has_bits) {
    (*has_bits)[0] |= 2048u;
  }
  static void set_has_component(HasBits* has_bits) {
    (*has_bits)[0] |= 4096u;
  }
  static void set_has_bits(HasBits* has_bits) {
    (*has_bits)[0] |= 8192u;
  }
  static void set_has_as_is(HasBits* has_bits) {
    (*has_bits)[0] |= 16384u;
  }
  static void set_has_pixel_type(HasBits* has_bits) {
    (*has_bits)[0] |= 32768u;
  }
  static void set_has_filenamesize(HasBits* has_bits) {
    (*has_bits)[0] |= 65536u;
  }
  static void set_has_filenamedata(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_datasize(HasBits* has_bits) {
    (*has_bits)[0] |= 131072u;
  }
  static void set_has_podata(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
};

textureData_proto::textureData_proto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned),
  md5_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:textureData_proto)
}
textureData_proto::textureData_proto(const textureData_proto& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(),
      _has_bits_(from._has_bits_),
      md5_(from.md5_) {
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  filenamedata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_filenamedata()) {
    filenamedata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_filenamedata(), 
      GetArenaForAllocation());
  }
  podata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_podata()) {
    podata_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_podata(), 
      GetArenaForAllocation());
  }
  ::memcpy(&enabled_, &from.enabled_,
    static_cast<size_t>(reinterpret_cast<char*>(&datasize_) -
    reinterpret_cast<char*>(&enabled_)) + sizeof(datasize_));
  // @@protoc_insertion_point(copy_constructor:textureData_proto)
}

inline void textureData_proto::SharedCtor() {
filenamedata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
podata_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&enabled_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&datasize_) -
    reinterpret_cast<char*>(&enabled_)) + sizeof(datasize_));
}

textureData_proto::~textureData_proto() {
  // @@protoc_insertion_point(destructor:textureData_proto)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<std::string>();
}

inline void textureData_proto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  filenamedata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  podata_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void textureData_proto::ArenaDtor(void* object) {
  textureData_proto* _this = reinterpret_cast< textureData_proto* >(object);
  (void)_this;
}
void textureData_proto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void textureData_proto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void textureData_proto::Clear() {
// @@protoc_insertion_point(message_clear_start:textureData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  md5_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      filenamedata_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      podata_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x000000fcu) {
    ::memset(&enabled_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&wrapt_) -
        reinterpret_cast<char*>(&enabled_)) + sizeof(wrapt_));
  }
  if (cached_has_bits & 0x0000ff00u) {
    ::memset(&eformat_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&pixel_type_) -
        reinterpret_cast<char*>(&eformat_)) + sizeof(pixel_type_));
  }
  if (cached_has_bits & 0x00030000u) {
    ::memset(&filenamesize_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&datasize_) -
        reinterpret_cast<char*>(&filenamesize_)) + sizeof(datasize_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* textureData_proto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional uint32 enabled = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          _Internal::set_has_enabled(&has_bits);
          enabled_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_TYPE textType = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_texttype(static_cast<::textureData_proto_TEXTURE_TYPE>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_magfilter(static_cast<::textureData_proto_TEXTURE_MAG_FILTER>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_minfilter(static_cast<::textureData_proto_TEXTURE_MIN_FILTER>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_WRAP wrapS = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_wraps(static_cast<::textureData_proto_TEXTURE_WRAP>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_WRAP wrapT = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_wrapt(static_cast<::textureData_proto_TEXTURE_WRAP>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_EFORMAT eFormat = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_eformat(static_cast<::textureData_proto_TEXTURE_EFORMAT>(val));
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_NCOMPONENT nComponent = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_ncomponent(static_cast<::textureData_proto_TEXTURE_NCOMPONENT>(val));
        } else goto handle_unusual;
        continue;
      // optional uint32 width = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          _Internal::set_has_width(&has_bits);
          width_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 height = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          _Internal::set_has_height(&has_bits);
          height_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 component = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          _Internal::set_has_component(&has_bits);
          component_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 bits = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 96)) {
          _Internal::set_has_bits(&has_bits);
          bits_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 as_is = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 104)) {
          _Internal::set_has_as_is(&has_bits);
          as_is_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .textureData_proto.TEXTURE_COMPONENT pixel_type = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 112)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_pixel_type(static_cast<::textureData_proto_TEXTURE_COMPONENT>(val));
        } else goto handle_unusual;
        continue;
      // optional uint32 fileNameSize = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 120)) {
          _Internal::set_has_filenamesize(&has_bits);
          filenamesize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes fileNameData = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          auto str = _internal_mutable_filenamedata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional uint32 dataSize = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 136)) {
          _Internal::set_has_datasize(&has_bits);
          datasize_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated uint32 md5 = 18;
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 146)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_md5(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 144) {
          _internal_add_md5(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional bytes poData = 19;
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          auto str = _internal_mutable_podata();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<std::string>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* textureData_proto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:textureData_proto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // optional uint32 enabled = 1;
  if (_internal_has_enabled()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_enabled(), target);
  }

  // optional .textureData_proto.TEXTURE_TYPE textType = 2;
  if (_internal_has_texttype()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      2, this->_internal_texttype(), target);
  }

  // optional .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
  if (_internal_has_magfilter()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_magfilter(), target);
  }

  // optional .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
  if (_internal_has_minfilter()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_minfilter(), target);
  }

  // optional .textureData_proto.TEXTURE_WRAP wrapS = 5;
  if (_internal_has_wraps()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      5, this->_internal_wraps(), target);
  }

  // optional .textureData_proto.TEXTURE_WRAP wrapT = 6;
  if (_internal_has_wrapt()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      6, this->_internal_wrapt(), target);
  }

  // optional .textureData_proto.TEXTURE_EFORMAT eFormat = 7;
  if (_internal_has_eformat()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      7, this->_internal_eformat(), target);
  }

  // optional .textureData_proto.TEXTURE_NCOMPONENT nComponent = 8;
  if (_internal_has_ncomponent()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      8, this->_internal_ncomponent(), target);
  }

  // optional uint32 width = 9;
  if (_internal_has_width()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(9, this->_internal_width(), target);
  }

  // optional uint32 height = 10;
  if (_internal_has_height()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(10, this->_internal_height(), target);
  }

  // optional uint32 component = 11;
  if (_internal_has_component()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(11, this->_internal_component(), target);
  }

  // optional uint32 bits = 12;
  if (_internal_has_bits()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(12, this->_internal_bits(), target);
  }

  // optional uint32 as_is = 13;
  if (_internal_has_as_is()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(13, this->_internal_as_is(), target);
  }

  // optional .textureData_proto.TEXTURE_COMPONENT pixel_type = 14;
  if (_internal_has_pixel_type()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      14, this->_internal_pixel_type(), target);
  }

  // optional uint32 fileNameSize = 15;
  if (_internal_has_filenamesize()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(15, this->_internal_filenamesize(), target);
  }

  // optional bytes fileNameData = 16;
  if (_internal_has_filenamedata()) {
    target = stream->WriteBytesMaybeAliased(
        16, this->_internal_filenamedata(), target);
  }

  // optional uint32 dataSize = 17;
  if (_internal_has_datasize()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(17, this->_internal_datasize(), target);
  }

  // repeated uint32 md5 = 18;
  {
    int byte_size = _md5_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          18, _internal_md5(), byte_size, target);
    }
  }

  // optional bytes poData = 19;
  if (_internal_has_podata()) {
    target = stream->WriteBytesMaybeAliased(
        19, this->_internal_podata(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:textureData_proto)
  return target;
}

size_t textureData_proto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:textureData_proto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 md5 = 18;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt32Size(this->md5_);
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _md5_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    // optional bytes fileNameData = 16;
    if (cached_has_bits & 0x00000001u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_filenamedata());
    }

    // optional bytes poData = 19;
    if (cached_has_bits & 0x00000002u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
          this->_internal_podata());
    }

    // optional uint32 enabled = 1;
    if (cached_has_bits & 0x00000004u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_enabled());
    }

    // optional .textureData_proto.TEXTURE_TYPE textType = 2;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_texttype());
    }

    // optional .textureData_proto.TEXTURE_MAG_FILTER magFilter = 3;
    if (cached_has_bits & 0x00000010u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_magfilter());
    }

    // optional .textureData_proto.TEXTURE_MIN_FILTER minFilter = 4;
    if (cached_has_bits & 0x00000020u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_minfilter());
    }

    // optional .textureData_proto.TEXTURE_WRAP wrapS = 5;
    if (cached_has_bits & 0x00000040u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_wraps());
    }

    // optional .textureData_proto.TEXTURE_WRAP wrapT = 6;
    if (cached_has_bits & 0x00000080u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_wrapt());
    }

  }
  if (cached_has_bits & 0x0000ff00u) {
    // optional .textureData_proto.TEXTURE_EFORMAT eFormat = 7;
    if (cached_has_bits & 0x00000100u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_eformat());
    }

    // optional .textureData_proto.TEXTURE_NCOMPONENT nComponent = 8;
    if (cached_has_bits & 0x00000200u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_ncomponent());
    }

    // optional uint32 width = 9;
    if (cached_has_bits & 0x00000400u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_width());
    }

    // optional uint32 height = 10;
    if (cached_has_bits & 0x00000800u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_height());
    }

    // optional uint32 component = 11;
    if (cached_has_bits & 0x00001000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_component());
    }

    // optional uint32 bits = 12;
    if (cached_has_bits & 0x00002000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_bits());
    }

    // optional uint32 as_is = 13;
    if (cached_has_bits & 0x00004000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_as_is());
    }

    // optional .textureData_proto.TEXTURE_COMPONENT pixel_type = 14;
    if (cached_has_bits & 0x00008000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_pixel_type());
    }

  }
  if (cached_has_bits & 0x00030000u) {
    // optional uint32 fileNameSize = 15;
    if (cached_has_bits & 0x00010000u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_filenamesize());
    }

    // optional uint32 dataSize = 17;
    if (cached_has_bits & 0x00020000u) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
          this->_internal_datasize());
    }

  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void textureData_proto::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::PROTOBUF_NAMESPACE_ID::internal::DownCast<const textureData_proto*>(
      &from));
}

void textureData_proto::MergeFrom(const textureData_proto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:textureData_proto)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  md5_.MergeFrom(from.md5_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x000000ffu) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_filenamedata(from._internal_filenamedata());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_set_podata(from._internal_podata());
    }
    if (cached_has_bits & 0x00000004u) {
      enabled_ = from.enabled_;
    }
    if (cached_has_bits & 0x00000008u) {
      texttype_ = from.texttype_;
    }
    if (cached_has_bits & 0x00000010u) {
      magfilter_ = from.magfilter_;
    }
    if (cached_has_bits & 0x00000020u) {
      minfilter_ = from.minfilter_;
    }
    if (cached_has_bits & 0x00000040u) {
      wraps_ = from.wraps_;
    }
    if (cached_has_bits & 0x00000080u) {
      wrapt_ = from.wrapt_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x0000ff00u) {
    if (cached_has_bits & 0x00000100u) {
      eformat_ = from.eformat_;
    }
    if (cached_has_bits & 0x00000200u) {
      ncomponent_ = from.ncomponent_;
    }
    if (cached_has_bits & 0x00000400u) {
      width_ = from.width_;
    }
    if (cached_has_bits & 0x00000800u) {
      height_ = from.height_;
    }
    if (cached_has_bits & 0x00001000u) {
      component_ = from.component_;
    }
    if (cached_has_bits & 0x00002000u) {
      bits_ = from.bits_;
    }
    if (cached_has_bits & 0x00004000u) {
      as_is_ = from.as_is_;
    }
    if (cached_has_bits & 0x00008000u) {
      pixel_type_ = from.pixel_type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00030000u) {
    if (cached_has_bits & 0x00010000u) {
      filenamesize_ = from.filenamesize_;
    }
    if (cached_has_bits & 0x00020000u) {
      datasize_ = from.datasize_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void textureData_proto::CopyFrom(const textureData_proto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:textureData_proto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool textureData_proto::IsInitialized() const {
  return true;
}

void textureData_proto::InternalSwap(textureData_proto* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  md5_.InternalSwap(&other->md5_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &filenamedata_, GetArenaForAllocation(),
      &other->filenamedata_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &podata_, GetArenaForAllocation(),
      &other->podata_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(textureData_proto, datasize_)
      + sizeof(textureData_proto::datasize_)
      - PROTOBUF_FIELD_OFFSET(textureData_proto, enabled_)>(
          reinterpret_cast<char*>(&enabled_),
          reinterpret_cast<char*>(&other->enabled_));
}

std::string textureData_proto::GetTypeName() const {
  return "textureData_proto";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::textureData_proto* Arena::CreateMaybeMessage< ::textureData_proto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::textureData_proto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
